Migrated auth screen state to compose state.
Android-Academy-Global/advanced-2021-architecture-1 pull request #30
Opened 2022-12-07 20:45 UTC by shchahelski

Перевел состояние на экране auth.

2022-12-07 20:48 UTC, shchahelski commented on app/build.gradle
> -    implementation "androidx.core:core-ktx:1.6.0"
Попались на глаза и парочку решил безболезненно обновить.

2022-12-07 20:48 UTC, shchahelski commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/view/AuthView.kt
> +        emailError = if (emailError != null) stringResource(emailError) else "",
Вот тут самое интересное. Сейчас у нас есть один стейт `AuthState`, который хранит все про UI. Если посмотреть семплы от гугла, то там все на уровне UI разруливается через sealed class. И вот что делать? Как-то странно может получаться.

2022-12-07 20:48 UTC, shchahelski commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/viewmodel/AuthViewModel.kt
> +                    passwordError = null,
Из-за одного стейта приходится везде при копировании ресетать предыдущий стейт и делать новый. Может тогда и copy не надо делать, а сразу новый стейт в велью засовывать. Что думаете?

2022-12-07 20:57 UTC, shchahelski commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/view/AuthView.kt
> +    authState: AuthState,
И еще момент, стоит ли передавать именно стейт или лучше набор параметров нужных? потому что в доке они и говорят, чтобы легче можно было переиспользовать, то стоит типами простыми описывать или лямбды. Но мы тут не собираемся переиспользовать, поэтому наверное можно и так.

2022-12-08 09:47 UTC, Lingviston requested changes
Имхо критично поправить следующее:
- микс authState и отдельных полей в AuthView
- показ тоаста

2022-12-08 09:47 UTC, Lingviston commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/view/AuthView.kt
> +        emailError = if (emailError != null) stringResource(emailError) else "",
Не понимаю, почему это проблема именно здесь. Sealed interface это ок, если состояния реально взаимоисключающие. В противном случае - как это было у нас - они скорее мешают.

2022-12-08 09:47 UTC, Lingviston commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/view/AuthView.kt
> +    authState: AuthState,
Я создал 2 версии AuthView - первая stateful, принимает навигатор и VM; вторая stateless - принимает отдельные поля. Первая версия слушает state и приобразовывает его в отдельные поля. Так вот их не стоит миксовать! Поэтому из этой функции я бы полностью убрал AuthState.
Тут дело не только в переиспользовании, но и в простоте превью и отсутствии необходимости париться о мутабельности/стабильности AuthState.

2022-12-08 09:47 UTC, Lingviston commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/view/AuthView.kt
> +            onValueChange = { input -> emailInput = input },
В старой версии кода была логика, что если после показа ошибки пользователь начинает ввод - ошибка прячется. Это логику хотелось бы сохранить. Но ее конечно лучше было бы перенести в ВМ. А можно оставить и мою реализацию на View. Она конечно нарушает принцип single source of truth, но зато может послужить демонстрацией работы со стейтом на UI

2022-12-08 09:47 UTC, Lingviston commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/view/AuthView.kt
> +private fun ShowToastOnLoginErrorIfNeeded(loginError: Int?) {
Данная функция будет показывать тоаст при каждой рекомпозиции AuthView, внутри которой она используется. Это ожидаемо? Просто работает на честном слове :)
Можно посмотреть стандартный SnackbarHost. Пример тут https://developer.android.com/jetpack/compose/side-effects#launchedeffect

2022-12-08 09:47 UTC, Lingviston commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/viewmodel/AuthViewModel.kt
> +                    passwordError = null,
👍 Думаю надо от кейса к кейсу делать как удобнее. У нас тут не полноценный MVI

2022-12-12 23:12 UTC, shchahelski commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/view/AuthView.kt
> +    authState: AuthState,
Сделал как ты и отписал. Я просто в примерах у них видел зачастую через один стейт и потом же текст, что можно не стейтом, а примитивами, чтобы переиспользовать. Касательно стабильности стейта - это классный поинт.

2022-12-12 23:12 UTC, shchahelski commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/view/AuthView.kt
> +private fun ShowToastOnLoginErrorIfNeeded(loginError: Int?) {
Тоаст поправил тоже, спасибо! Надо разобраться с этими эффектами.

2022-12-13 21:31 UTC, Lingviston approved these changes

2022-12-13 21:31 UTC, Lingviston commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/view/AuthView.kt
> +                emailInput = input
Прям напрашивается исключительно для красоты и emailInput вынести во ViewModel

2022-12-13 21:31 UTC, Lingviston commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/viewmodel/AuthViewModel.kt
> +                isEmailErrorVisible = false,
На самом деле нам тут достаточно только Visible флаги менять

2022-12-14 18:07 UTC, shchahelski commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/view/AuthView.kt
> +                emailInput = input
И в этом случае что получается, каждый раз вызывать вью модель, сетать новое состояние email и соотвественно рекомпозиция будет вызываться? Я так понимаю, что этот input должен чуть выше сетаться

2022-12-14 18:08 UTC, shchahelski commented on app/src/main/java/ru/gaket/themoviedb/presentation/auth/viewmodel/AuthViewModel.kt
> +                isEmailErrorVisible = false,
Это на всякий случай ресетать все состояние я подумал.

2022-12-22 08:07 UTC, merged